# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/git/UTCN_CS_2nd_year/CA/practice_lab/lab02/combinational_shifter/combinational_shifter.cache/wt [current_project]
set_property parent.project_path D:/git/UTCN_CS_2nd_year/CA/practice_lab/lab02/combinational_shifter/combinational_shifter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/git/UTCN_CS_2nd_year/CA/practice_lab/lab02/combinational_shifter/combinational_shifter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/git/UTCN_CS_2nd_year/CA/practice_lab/lab02/combinational_shifter/combinational_shifter.srcs/sources_1/new/combinational_shifter.vhd
  D:/git/UTCN_CS_2nd_year/CA/practice_lab/lab02/combinational_shifter/combinational_shifter.srcs/sources_1/new/shifter_tester.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/git/UTCN_CS_2nd_year/CA/practice_lab/lab02/combinational_shifter/combinational_shifter.srcs/constrs_1/imports/new/basys3.xdc
set_property used_in_implementation false [get_files D:/git/UTCN_CS_2nd_year/CA/practice_lab/lab02/combinational_shifter/combinational_shifter.srcs/constrs_1/imports/new/basys3.xdc]


synth_design -top shifter_tester -part xc7a35tcpg236-1


write_checkpoint -force -noxdef shifter_tester.dcp

catch { report_utilization -file shifter_tester_utilization_synth.rpt -pb shifter_tester_utilization_synth.pb }
