# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab6/mips_gr/mips_gr.cache/wt [current_project]
set_property parent.project_path C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab6/mips_gr/mips_gr.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab6/mips_gr/mips_gr.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab6/mips_gr/mips_gr.srcs/sources_1/imports/new/regf.vhd
  C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab6/mips_gr/mips_gr.srcs/sources_1/imports/labs/lab4/mips_ram/mips_ram.srcs/sources_1/new/rom.vhd
  C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab6/mips_gr/mips_gr.srcs/sources_1/imports/labs/lab2/segmgent7/segmgent7.srcs/sources_1/new/segment7.vhd
  C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab6/mips_gr/mips_gr.srcs/sources_1/imports/labs/lab1/test_env/test_env.srcs/sources_1/new/mpg.vhd
  C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab6/mips_gr/mips_gr.srcs/sources_1/imports/labs/lab4/mips_ram/mips_ram.srcs/sources_1/new/mips_top.vhd
  C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab6/mips_gr/mips_gr.srcs/sources_1/new/inst_data.vhd
  C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab6/mips_gr/mips_gr.srcs/sources_1/new/control.vhd
  C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab6/mips_gr/mips_gr.srcs/sources_1/new/mips_gr.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab6/mips_gr/mips_gr.srcs/constrs_1/imports/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab6/mips_gr/mips_gr.srcs/constrs_1/imports/new/constraints.xdc]


synth_design -top mips_gr -part xc7a35tcpg236-1


write_checkpoint -force -noxdef mips_gr.dcp

catch { report_utilization -file mips_gr_utilization_synth.rpt -pb mips_gr_utilization_synth.pb }
