# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab2/comb_shift/comb_shift.cache/wt [current_project]
set_property parent.project_path C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab2/comb_shift/comb_shift.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab2/comb_shift/comb_shift.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab2/comb_shift/comb_shift.srcs/sources_1/new/shifter.vhd
  C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab2/comb_shift/comb_shift.srcs/sources_1/new/shift_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab2/comb_shift/comb_shift.srcs/constrs_1/imports/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/AErika/Documents/2nd/2nd_sem/CA/labs/lab2/comb_shift/comb_shift.srcs/constrs_1/imports/new/constraints.xdc]


synth_design -top shift_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef shift_top.dcp

catch { report_utilization -file shift_top_utilization_synth.rpt -pb shift_top_utilization_synth.pb }
